services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trends.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: trends.settings
      - key: SECRET_KEY
        value: 'django-insecure-)$$&@2#p--dw%tei2h3_5#_)6*tp)9t4y63tbff_mh3wr0$-r$'  # Replace with your actual secret key
      - key: ALLOWED_HOSTS
        value: 'trends-s829.onrender.com'
