services:
  - type: web
    name: trends
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate app
    startCommand: "gunicorn trends.wsgi --bind 0.0.0.0:$PORT"

