# Generated by Django 5.0.7 on 2024-07-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='cover_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
